name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: python /app/manage.py test

  deploy:
    needs: test 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 104.248.10.44
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |

          cd ./myenv/django_app/app
          source ./myenv/bin/activate
          git pull
          python manage.py migrate
          python manage.py collectstatic --noinput
          supervisorctl restart all

